name: C/C++ CI
on: [push, pull_request]

jobs:

  build-macos-macports-qt6:
    name: Build macOS MacPorts Qt 6
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1.2.0
      - name: Install macports
        run: |
          wget https://github.com/macports/macports-base/releases/download/v2.7.1/MacPorts-2.7.1-10.15-Catalina.pkg
          sudo installer -pkg ./MacPorts-2.7.1-10.15-Catalina.pkg -target /
      - name: Uninstall homebrew
        run: |
          curl -sLO https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh
          chmod +x ./uninstall.sh
          sudo ./uninstall.sh --force
      - name: Update macports
        run: sudo /opt/local/bin/port -v selfupdate
      - name: Install packages
        run: >
          sudo /opt/local/bin/port -N -p install
          wget
          gettext
          glib2
          pkgconfig
          cmake
          boost
          protobuf-cpp
          sqlite3
          gnutls
          chromaprint
          fftw
          taglib
          libcdio
          libmtp

      - name: Install gstreamer
        run: sudo /opt/local/bin/port -N -p install gstreamer1 gstreamer1-gst-plugins-base gstreamer1-gst-plugins-good gstreamer1-gst-plugins-bad gstreamer1-gst-plugins-ugly gstreamer1-gst-libav

      - name: Install qt6-qtbase
        run: sudo /opt/local/bin/port -N -p install qt6-qtbase

      - name: Install qt6-qttools
        run: sudo /opt/local/bin/port -N -p install qt6-qttools || echo ""

      - name: Install qt6-sqlite-plugin
        run: sudo /opt/local/bin/port -N -p install qt6-sqlite-plugin

      - name: Install libgpod
        run: sudo /opt/local/bin/port -N -p install libgpod || echo ""

      - name: Install create-dmg
        shell: bash
        run: |
          mkdir -p ~/build
          cd ~/build
          git clone https://github.com/create-dmg/create-dmg
          cd create-dmg
          sudo make install

      - name: Create Build Environment
        shell: bash
        run: /opt/local/bin/cmake -E make_directory build
      - name: Configure CMake
        shell: bash
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.15
          PKG_CONFIG_PATH: /opt/local/lib/pkgconfig
          GIO_EXTRA_MODULES: /opt/local/lib/gio/modules
          GST_PLUGIN_SCANNER: /opt/local/libexec/gstreamer-1.0/gst-plugin-scanner
          GST_PLUGIN_PATH: /opt/local/lib/gstreamer-1.0
        working-directory: build
        run: /opt/local/bin/cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_WITH_QT6=ON -DBUILD_WERROR=ON -DUSE_BUNDLE=ON -DCMAKE_PREFIX_PATH=/opt/local/lib/cmake
      - name: Build
        working-directory: build
        shell: bash
        run: /opt/local/bin/cmake --build . --config Release --parallel 4
      - name: Install
        working-directory: build
        shell: bash
        run: make install
      - name: Fix macdeployqt and macdeploycheck
        working-directory: build
        shell: bash
        run: |
          install_name_tool -change "@rpath/QtCore.framework/Versions/A/QtCore" "/opt/local/libexec/qt6/lib/QtCore.Framework/Versions/A/QtCore" 3rdparty/macdeployqt/macdeployqt
          install_name_tool -change "@rpath/QtCore.framework/Versions/A/QtCore" "/opt/local/libexec/qt6/lib/QtCore.Framework/Versions/A/QtCore" ext/macdeploycheck/macdeploycheck
      - name: Deploy
        working-directory: build
        shell: bash
        run: make deploy
      - name: Deploy check
        working-directory: build
        shell: bash
        run: make deploycheck
      - name: Create DMG
        working-directory: build
        shell: bash
        run: make dmg
